linters-settings:
  dupl:
    threshold: 150
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 32
  goimports:
    local-prefixes: github.com/pamburus
  govet:
    check-shadowing: false
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # Please, do not use `enable-all`: it's deprecated and will be removed soon.
  # Inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint.
  disable-all: true
  enable:
    - asciicheck
    - dupl
    - errcheck
    - exportloopref
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nlreturn
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - vet
    - vetshadow
    - whitespace

issues:
  # Disable this option because it causes golint to hide almost all issues.
  exclude-use-default: false
  # Excluding configuration per-path, per-linter, per-text and per-source.
  exclude-rules:
    # The dot-imports linter is disabled for the test files because it is convenient to dot-import third-party testing frameworks.
    - linters: [revive]
      text: '^dot-imports: '
      paths:
        - '*_test.go'
    # The staticcheck linter reports that `nil` context is passed, but it is intentionally done for the sake of the tests.
    - linters: [staticcheck]
      text: '^SA1012:'
      paths:
        - '*_test.go'
    # The duplicate lines in the benchmark_test.go file are expected because any attempt to deduplicate them would affect the performance of the benchmark.
    - linters: [dupl]
      text: 'lines are duplicate'
      paths:
        - 'benchmark_test.go'
